In [1]:
from ARS import *

In [2]:
n_steps=0
n_charges=6
scan_name="2_2_2_new"
cubes_dir="/home/boittier/v1"
output_dir="water0_bi_2_2_2_new"
frames="/home/boittier/AdjustReference-System/frames.txt"
initial_fit_cube="/home/boittier/v1/2_2_2_new"
pcube = cubes_dir + "/2_2_2_new.com.chk.p.cube"
frame = frames
pcube2 = pcube
method = "bisector"

def print_vals(ars_obj):
    print("local c pos.\n", ars_obj.get_c_positions_local())
    print("charge_atom_associations\n", ars_obj.charge_atom_associations)

#  Testing X axes

In [3]:
initial_fit="/home/boittier/AdjustReference-System/test_x.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

local c pos.
 [[ 3.28557238e-01 -2.80129161e-06 -1.41009671e-01]
 [ 3.32657128e-02 -2.84310960e-05 -7.48222582e-02]]
charge_atom_associations
 [[0, 2], [1, 2]]


In [4]:
ars_obj.set_local_charge_positions(np.array([[0.1,0,0], [-0.1,0,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_x.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_x.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.1  0.   0. ]
 [-0.1  0.   0. ]]
local c pos.
 [[ 1.00000000e-01  0.00000000e+00 -4.85722573e-17]
 [-1.00000000e-01  0.00000000e+00  1.38777878e-17]]
charge_atom_associations
 [[0, 2], [1, 2]]


In [5]:
ars_obj.set_local_charge_positions(np.array([[0,0.1,0], [0,-0.1,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_x.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_x.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.1  0. ]
 [ 0.  -0.1  0. ]]
local c pos.
 [[ 4.40517460e-17  1.00000000e-01  3.37776788e-17]
 [ 4.40517460e-17 -1.00000000e-01  3.37776788e-17]]
charge_atom_associations
 [[0, 2], [1, 2]]


In [6]:
ars_obj.set_local_charge_positions(np.array([[0,0,0.1], [0,0,-0.1]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_x.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_x.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.   0.1]
 [ 0.   0.  -0.1]]
local c pos.
 [[-6.24500451e-17  0.00000000e+00  1.00000000e-01]
 [ 6.24500451e-17  0.00000000e+00 -1.00000000e-01]]
charge_atom_associations
 [[0, 2], [1, 2]]


# Testing Y axes

In [7]:
initial_fit="/home/boittier/AdjustReference-System/test_y.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
# print_vals(ars_obj)

In [8]:
ars_obj.set_local_charge_positions(np.array([[0.1,0,0], [-0.1,0,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_y.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_y.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.1  0.   0. ]
 [-0.1  0.   0. ]]
local c pos.
 [[ 1.00000000e-01  0.00000000e+00  4.85722573e-17]
 [-1.00000000e-01  0.00000000e+00 -1.38777878e-17]]
charge_atom_associations
 [[0, 1], [1, 1]]


In [9]:
ars_obj.set_local_charge_positions(np.array([[0,0.1,0], [0,-0.1,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_y.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_y.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.1  0. ]
 [ 0.  -0.1  0. ]]
local c pos.
 [[ 4.40517460e-17  1.00000000e-01 -3.37776788e-17]
 [ 4.40517460e-17 -1.00000000e-01 -3.37776788e-17]]
charge_atom_associations
 [[0, 1], [1, 1]]


In [10]:
ars_obj.set_local_charge_positions(np.array([[0,0,0.1], [0,0,-0.1]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_y.xyz"))
initial_fit="/home/boittier/AdjustReference-System/global_test_y.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.   0.1]
 [ 0.   0.  -0.1]]
local c pos.
 [[ 6.24500451e-17  0.00000000e+00  1.00000000e-01]
 [-6.24500451e-17  0.00000000e+00 -1.00000000e-01]]
charge_atom_associations
 [[0, 1], [1, 1]]


#  Testing Z axes

In [11]:
initial_fit="/home/boittier/AdjustReference-System/test_z.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
# print_vals(ars_obj)

In [12]:
ars_obj.set_local_charge_positions(np.array([[0.1,0,0], [-0.1,0,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_z.xyz"))

initial_fit="/home/boittier/AdjustReference-System/global_test_z.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.1  0.   0. ]
 [-0.1  0.   0. ]]
local c pos.
 [[ 0.1  0.   0. ]
 [-0.1  0.   0. ]]
charge_atom_associations
 [[0, 0], [1, 0]]


In [13]:
ars_obj.set_local_charge_positions(np.array([[0,0.1,0], [0,-0.1,0]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_z.xyz"))

initial_fit="/home/boittier/AdjustReference-System/global_test_z.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.1  0. ]
 [ 0.  -0.1  0. ]]
local c pos.
 [[ 0.   0.1  0. ]
 [ 0.  -0.1  0. ]]
charge_atom_associations
 [[0, 0], [1, 0]]


In [14]:
ars_obj.set_local_charge_positions(np.array([[0,0,0.1], [0,0,-0.1]])) 
print("set local positions: \n", ars_obj.get_c_positions_local())
cp = ars_obj.local_to_global()
ars_obj.set_charge_positions_plus(cp)
ars_obj.save_charges_global(os.path.join("/home/boittier/AdjustReference-System", "test_z.xyz"))

initial_fit="/home/boittier/AdjustReference-System/global_test_z.xyz"
xyz = initial_fit
ars_obj = ARS(xyz, pcube, frames, pcube_2=pcube, method=method)
print_vals(ars_obj)

set local positions: 
 [[ 0.   0.   0.1]
 [ 0.   0.  -0.1]]
local c pos.
 [[ 0.   0.   0.1]
 [ 0.   0.  -0.1]]
charge_atom_associations
 [[0, 0], [1, 0]]
